# Generated by Django 5.2.1 on 2025-06-03 02:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('artist', models.CharField(max_length=100)),
                ('location', models.TextField()),
                ('description', models.TextField()),
                ('rsvp_link', models.URLField()),
                ('isSelected', models.BooleanField(default=False)),
            ],
        ),
    ]
