# Generated by Django 5.2.1 on 2025-06-04 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='dj_images/')),
                ('artist', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('isSelected', models.BooleanField(default=False)),
                ('isSpotlight', models.BooleanField(default=False)),
                ('isDeleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('isSelected', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Mix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('audio', models.FileField(upload_to='mixes/')),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='mix_images/')),
                ('isSelected', models.BooleanField(default=False)),
                ('isLatest', models.BooleanField(default=False)),
            ],
        ),
    ]
