# Generated by Django 5.2.1 on 2025-06-05 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0002_dj_galleryimg_mix'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dj',
            old_name='isDeleted',
            new_name='isDelete',
        ),
        # migrations.RenameField(
        #     model_name='mix',
        #     old_name='is_latest',
        #     new_name='isLatest',
        # ),
        migrations.AddField(
            model_name='event',
            name='isDelete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='galleryimg',
            name='isDelete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mix',
            name='isDelete',
            field=models.BooleanField(default=False),
        ),
    ]
