# Generated by Django 5.2.1 on 2025-06-05 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0003_rename_isdeleted_dj_isdelete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimg',
            name='image',
            field=models.ImageField(upload_to='gallery/'),
        ),
    ]
