# Generated by Django 5.2.1 on 2025-06-06 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0005_remove_event_artist_event_artists'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='isUpcoming',
            field=models.BooleanField(default=False),
        ),
    ]
