# Generated by Django 5.2.1 on 2025-06-08 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0006_event_isupcoming'),
    ]

    operations = [
        migrations.AddField(
            model_name='dj',
            name='socialmedia',
            field=models.CharField(default='', max_length=255),
        ),
    ]
