# Generated by Django 5.2.1 on 2025-08-12 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0008_event_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dj',
            old_name='socialmedia',
            new_name='socialMedia',
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
